---

# https://cloud.google.com/sdk/docs/install#deb

- name: prereq packages
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
      - curl
    state: present
    update_cache: yes

- name: DEPRECATED get google key, add to deprecated trusted keyring
  shell: curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

- name: get google key, save in /usr/share/keyrings for newer apt deb syntax
  get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /usr/share/keyrings/google.gpg
    mode: ugo+rw

- name: add google apt repository
  apt_repository:
    repo: "deb [arch=amd64, signed-by=/usr/share/keyrings/google.gpg] https://packages.cloud.google.com/apt cloud-sdk main"
    state: present
    filename: google-cloud-sdk
    update_cache: yes
    mode: 0644
    validate_certs: no

- name: install gcloud package
  package:
    name:
      #- google-cloud-sdk # already on GCP VM as SNAP
      - kubectl
      - google-cloud-sdk-gke-gcloud-auth-plugin
    state: present
    update_cache: yes

