---

- hosts: jumpboxes
  become: yes
  roles:
    - minimal-jumpbox-setup
    - k9s
    - helm3-apt

    # gcloud is already on GCP VM instances, BUT as Snap which does not have gke auth plugin
    - gcloud-apt

