---

- name: DEPRECATED get helm3 key, add to deprected trusted keyring
  apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present

- name: get helm3 key, save in /usr/share/keyrings for newer apt deb syntax
  get_url:
    url: https://baltocdn.com/helm/signing.asc
    dest: /usr/share/keyrings/helm3.asc
    mode: ugo+rw

- name: add helm3 apt repository
  apt_repository:
    repo: deb [arch=amd64, signed-by=/usr/share/keyrings/helm3.asc] https://baltocdn.com/helm/stable/debian/ all main
    state: present
    filename: helm3
    update_cache: yes
    mode: 0644
    validate_certs: false

- name: install helm apt package
  apt:
    update_cache: true
    pkg:
    - apt-transport-https
    - helm
    state: present

- name: create Debian/Ubuntu alternative for helm
  command: update-alternatives --install /usr/local/bin/helm helm /usr/sbin/helm 20
  register: command_result
  changed_when: "command_result.stdout != ''"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: create symlink for helm in PATH location for non Debian systems
  file:
    src: /usr/sbin/helm
    dest: /usr/local/bin/helm
    state: link
  when: not (ansible_distribution == 'Debian' and ansible_distribution == 'Ubuntu')
